version: '3.8'

services:
  fs-server:
    build: .
    container_name: fs-server
    ports:
      - '3000:8080'
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=pinkystore

      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pinkystore
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - '6379:6379'
    networks:
      - app-network
volumes:
  pgdata:

networks:
  app-network:
