export enum SocketEvent {
  ORDER_PAYMENT_EXPIRED = 'ORDER_PAYMENT_EXPIRED',
  USER_CONNECTED = 'USER_CONNECTED',
  USER_DISCONNECTED = 'USER_DISCONNECTED',
  ORDER_STATUS_UPDATED = 'ORDER_STATUS_UPDATED',
  PAYMENT_SUCCESSFUL = 'PAYMENT_SUCCESSFUL',
}
